export interface SummaryRequest {
  text: string;
  length: 'short' | 'medium' | 'long';
  includeKeyPoints: boolean;
}

export interface SummaryResponse {
  summary: string;
  keyPoints: string[];
}

export class SummaryGenerator {
  static async generateSummary(request: SummaryRequest): Promise<SummaryResponse> {
    // Mock AI summary - works without API key
    const lengthText = {
      short: 'brief summary',
      medium: 'comprehensive overview', 
      long: 'detailed analysis'
    };

    const mockSummary = `This is a ${lengthText[request.length]} generated by the AI system. The document contains important information that has been processed and summarized effectively.

Key insights from the document have been extracted to provide you with a clear understanding of the main content and essential points.`;

    const mockKeyPoints = [
      'Document successfully processed and analyzed',
      'Main themes and concepts identified',
      'Key information extracted for quick reference',
      'Summary tailored to requested length preference'
    ];

    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    return {
      summary: mockSummary,
      keyPoints: request.includeKeyPoints ? mockKeyPoints : []
    };
  }
}